services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Данные БД хранятся вне контейнера (в volume)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    # Команда запуска: собираем статику, делаем миграции и запускаем WSGI-сервер Gunicorn
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app # Монтируем код (чтобы линтер и тесты видели актуальные файлы)
      - static_volume:/app/static # Шарим статику с Nginx
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: