# Generated by Django 6.0.3 on 2026-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('is_foldable', models.BooleanField(default=False, verbose_name='Складной')),
                ('length', models.FloatField(verbose_name='Длина (см)')),
                ('width', models.FloatField(verbose_name='Ширина (см)')),
                ('material', models.CharField(choices=[('дерево', 'Дерево'), ('стекло', 'Стекло'), ('металл', 'Металл'), ('пластик', 'Пластик')], max_length=20, verbose_name='Материал')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес (кг)')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
    ]
