# Generated by Django 5.2.13 on 2026-04-07 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_table_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.AlterField(
            model_name='table',
            name='brand',
            field=models.CharField(max_length=100, unique=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='table',
            name='length',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Длина (см)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='width',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Ширина (см)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.tablematerial', verbose_name='Материал'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('length__gt', 0)), name='check_positive_length'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0)), name='check_positive_width'),
        ),
    ]
