# Generated by Django 5.2.13 on 2026-04-07 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tablematerial_alter_table_brand_alter_table_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
            ],
        ),
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='table',
            name='check_positive_length',
        ),
        migrations.RemoveConstraint(
            model_name='table',
            name='check_positive_width',
        ),
        migrations.AddField(
            model_name='table',
            name='large_wholesale_price',
            field=models.DecimalField(decimal_places=2, default=900.0, max_digits=10, verbose_name='Цена (крупный опт)'),
        ),
        migrations.AddField(
            model_name='table',
            name='large_wholesale_threshold',
            field=models.PositiveIntegerField(default=50, verbose_name='Крупный опт от (шт)'),
        ),
        migrations.AddField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Цена за 1 шт'),
        ),
        migrations.AddField(
            model_name='table',
            name='small_wholesale_price',
            field=models.DecimalField(decimal_places=2, default=950.0, max_digits=10, verbose_name='Цена (мелкий опт)'),
        ),
        migrations.AddField(
            model_name='table',
            name='small_wholesale_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Мелкий опт от (шт)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tablematerial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.table'),
        ),
    ]
